a= input( 'Digite algo?')
print('Tipo primitivo é', type(a) )
print('Só tem espaço',a.isspace())
print('É um numero',a.isnumeric())
print('É alfabetico',a.isalpha())
print('È alfanumerico?',a.isalnum())
print('Esta em Maiúsculo?',a.isupper())
print('Esta em minusculo?',a.islower())
print('Esta capitalizada?',a.istitle())
